-- Dennokun database schema
-- PostgreSQL 15+ initial schema for local development

BEGIN;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    permissions JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_unique ON users (email);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    start_date DATE,
    spreadsheet_id TEXT,
    bucket_name TEXT,
    flash_news_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_events_start_date ON events (start_date);
CREATE INDEX IF NOT EXISTS idx_events_name ON events (name);

CREATE TABLE IF NOT EXISTS event_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    order_number INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_event_sections_event_id ON event_sections (event_id);
CREATE INDEX IF NOT EXISTS idx_event_sections_event_id_order_number ON event_sections (event_id, order_number);

CREATE TABLE IF NOT EXISTS event_schools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    name_aliases TEXT[],
    order_number INTEGER,
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_event_schools_event_id ON event_schools (event_id);
CREATE INDEX IF NOT EXISTS idx_event_schools_event_id_name ON event_schools (event_id, name);

CREATE TABLE IF NOT EXISTS event_team_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_event_team_groups_event_id ON event_team_groups (event_id);

CREATE TABLE IF NOT EXISTS event_teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    event_section_id BIGINT REFERENCES event_sections(id) ON DELETE SET NULL,
    event_school_id BIGINT REFERENCES event_schools(id) ON DELETE SET NULL,
    team_group_id BIGINT REFERENCES event_team_groups(id) ON DELETE SET NULL,
    is_seed BOOLEAN NOT NULL DEFAULT FALSE,
    order_of_application INTEGER,
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_event_teams_event_id ON event_teams (event_id);
CREATE INDEX IF NOT EXISTS idx_event_teams_event_id_name ON event_teams (event_id, name);
CREATE INDEX IF NOT EXISTS idx_event_teams_event_id_team_group_id ON event_teams (event_id, team_group_id);
CREATE INDEX IF NOT EXISTS idx_event_teams_event_section_id ON event_teams (event_section_id);
CREATE INDEX IF NOT EXISTS idx_event_teams_event_school_id ON event_teams (event_school_id);

CREATE TABLE IF NOT EXISTS event_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    order_number INTEGER,
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_event_rooms_event_id ON event_rooms (event_id);
CREATE INDEX IF NOT EXISTS idx_event_rooms_event_id_order_number ON event_rooms (event_id, order_number);

CREATE TABLE IF NOT EXISTS event_timetable_segments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    name_aliases TEXT[],
    start_time TEXT,
    end_time TEXT,
    order_number INTEGER,
    is_pre_round BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_event_timetable_segments_event_id ON event_timetable_segments (event_id);
CREATE INDEX IF NOT EXISTS idx_event_timetable_segments_event_id_order_number ON event_timetable_segments (event_id, order_number);

CREATE TABLE IF NOT EXISTS event_staffs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    can_be_main_judge BOOLEAN NOT NULL DEFAULT FALSE,
    can_be_sub_judge BOOLEAN NOT NULL DEFAULT FALSE,
    can_be_timekeeper BOOLEAN NOT NULL DEFAULT FALSE,
    order_of_application INTEGER,
    note TEXT,
    present_timetable_segments_raw_value TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_event_staffs_event_id ON event_staffs (event_id);
CREATE INDEX IF NOT EXISTS idx_event_staffs_event_id_name ON event_staffs (event_id, name);

CREATE TABLE IF NOT EXISTS event_staff_present_timetable_segments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_timetable_segment_id BIGINT NOT NULL REFERENCES event_timetable_segments(id) ON DELETE CASCADE,
    event_staff_id BIGINT NOT NULL REFERENCES event_staffs(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_staff_present_unique ON event_staff_present_timetable_segments (event_timetable_segment_id, event_staff_id);
CREATE INDEX IF NOT EXISTS idx_staff_present_event_timetable_segment_id ON event_staff_present_timetable_segments (event_timetable_segment_id);
CREATE INDEX IF NOT EXISTS idx_staff_present_event_staff_id ON event_staff_present_timetable_segments (event_staff_id);

CREATE TABLE IF NOT EXISTS event_staff_interested_schools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_school_id BIGINT NOT NULL REFERENCES event_schools(id) ON DELETE CASCADE,
    event_staff_id BIGINT NOT NULL REFERENCES event_staffs(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_staff_schools_unique ON event_staff_interested_schools (event_school_id, event_staff_id);
CREATE INDEX IF NOT EXISTS idx_staff_schools_event_school_id ON event_staff_interested_schools (event_school_id);
CREATE INDEX IF NOT EXISTS idx_staff_schools_event_staff_id ON event_staff_interested_schools (event_staff_id);

CREATE TABLE IF NOT EXISTS event_staff_interested_teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_team_id BIGINT NOT NULL REFERENCES event_teams(id) ON DELETE CASCADE,
    event_staff_id BIGINT NOT NULL REFERENCES event_staffs(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_staff_teams_unique ON event_staff_interested_teams (event_team_id, event_staff_id);
CREATE INDEX IF NOT EXISTS idx_staff_teams_event_team_id ON event_staff_interested_teams (event_team_id);
CREATE INDEX IF NOT EXISTS idx_staff_teams_event_staff_id ON event_staff_interested_teams (event_staff_id);

CREATE TABLE IF NOT EXISTS event_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    event_timetable_segment_id BIGINT REFERENCES event_timetable_segments(id) ON DELETE SET NULL,
    event_room_id BIGINT REFERENCES event_rooms(id) ON DELETE SET NULL,
    event_section_id BIGINT REFERENCES event_sections(id) ON DELETE SET NULL,
    judges_assignment_count INTEGER,
    is_timekeeper_available BOOLEAN,
    main_judge_staff_id BIGINT REFERENCES event_staffs(id) ON DELETE SET NULL,
    sub_judge1_staff_id BIGINT REFERENCES event_staffs(id) ON DELETE SET NULL,
    sub_judge2_staff_id BIGINT REFERENCES event_staffs(id) ON DELETE SET NULL,
    sub_judge3_staff_id BIGINT REFERENCES event_staffs(id) ON DELETE SET NULL,
    sub_judge4_staff_id BIGINT REFERENCES event_staffs(id) ON DELETE SET NULL,
    timekeeper_staff_id BIGINT REFERENCES event_staffs(id) ON DELETE SET NULL,
    aff_team_id BIGINT REFERENCES event_teams(id) ON DELETE SET NULL,
    neg_team_id BIGINT REFERENCES event_teams(id) ON DELETE SET NULL,
    aff_votes INTEGER,
    neg_votes INTEGER,
    aff_constructive_comm INTEGER,
    aff_question_comm INTEGER,
    aff_answer_comm INTEGER,
    aff_first_rebuttal_comm INTEGER,
    aff_second_rebuttal_comm INTEGER,
    neg_constructive_comm INTEGER,
    neg_question_comm INTEGER,
    neg_answer_comm INTEGER,
    neg_first_rebuttal_comm INTEGER,
    neg_second_rebuttal_comm INTEGER,
    aff_comm_sum INTEGER,
    neg_comm_sum INTEGER,
    aff_manner INTEGER,
    neg_manner INTEGER,
    is_staffs_fixed BOOLEAN NOT NULL DEFAULT FALSE,
    is_result_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    order_number_in_segment INTEGER,
    note TEXT,
    aff_won INTEGER,
    neg_won INTEGER,
    name TEXT,
    tournament_weight INTEGER NOT NULL DEFAULT 0,
    is_result_public BOOLEAN NOT NULL DEFAULT FALSE,
    aff_pre_round_rank INTEGER,
    neg_pre_round_rank INTEGER,
    generation_run_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_event_matches_event_id_event_timetable_segment_id ON event_matches (event_id, event_timetable_segment_id);
CREATE INDEX IF NOT EXISTS idx_event_matches_event_id_event_room_id ON event_matches (event_id, event_room_id);
CREATE INDEX IF NOT EXISTS idx_event_matches_aff_team_id ON event_matches (aff_team_id);
CREATE INDEX IF NOT EXISTS idx_event_matches_neg_team_id ON event_matches (neg_team_id);
CREATE INDEX IF NOT EXISTS idx_event_matches_event_id_order_number_in_segment ON event_matches (event_id, order_number_in_segment);
CREATE INDEX IF NOT EXISTS idx_event_matches_event_id_is_staffs_fixed ON event_matches (event_id, is_staffs_fixed);
CREATE INDEX IF NOT EXISTS idx_event_matches_generation_run_id ON event_matches (generation_run_id);

CREATE TABLE IF NOT EXISTS event_match_voting_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_match_id BIGINT NOT NULL REFERENCES event_matches(id) ON DELETE CASCADE,
    judge_index INTEGER NOT NULL,
    aff_won INTEGER,
    neg_won INTEGER,
    aff_constructive_comm INTEGER,
    aff_question_comm INTEGER,
    aff_answer_comm INTEGER,
    aff_first_rebuttal_comm INTEGER,
    aff_second_rebuttal_comm INTEGER,
    neg_constructive_comm INTEGER,
    neg_question_comm INTEGER,
    neg_answer_comm INTEGER,
    neg_first_rebuttal_comm INTEGER,
    neg_second_rebuttal_comm INTEGER,
    aff_comm_sum INTEGER,
    neg_comm_sum INTEGER,
    aff_manner INTEGER,
    neg_manner INTEGER,
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_event_match_voting_details_event_match_id ON event_match_voting_details (event_match_id);
CREATE INDEX IF NOT EXISTS idx_event_match_voting_details_judge_index ON event_match_voting_details (judge_index);

COMMIT;
